#!/bin/bash
set -x
source /srsLTE.env
$SRS_UE_BINARY \
    $SRS_UE_USIM_OPTS \
    --usim.algo=$SRS_UE_USIM_ALGO \
    --nas.apn=$SRS_UE_NAS_APN \
    --rf.device_name=$SRS_UE_DEVICE_NAME \
    --rf.device_args=$SRS_UE_DEVICE_ARGS \
    $SRS_UE_CONFIG